PCA 분석

In [32]:
import numpy as np
import pandas as pd


#데이터 로드
data = pd.read_csv('result.csv', encoding ='euc-kr')

x_data = data.iloc[:, 1:-1]
y_data = data.iloc[:,-1]
x_data

,culture,build1,build2,build3,build4,build5,build6,build7
0,0.029197,0.505556,0.171429,0.000000,0.160920,0.157480,0.329399,0.057762
1,0.007299,0.411111,0.057143,0.148148,0.022989,0.102362,0.295422,0.043321
2,0.029197,0.500000,0.085714,0.148148,0.103448,0.118110,0.447783,0.032491
3,0.021898,0.316667,0.095238,0.037037,0.126437,0.086614,0.340486,0.010830
4,0.000000,0.405556,0.057143,0.074074,0.011494,0.031496,0.244993,0.043321
...,...,...,...,...,...,...,...,...
513,0.000000,0.244444,0.009524,0.000000,0.022989,0.007874,0.017883,0.003610
514,0.007299,0.216667,0.057143,0.037037,0.022989,0.023622,0.045422,0.021661
515,0.029197,0.200000,0.095238,0.037037,0.022989,0.039370,0.061874,0.007220
516,0.058394,0.700000,0.219048,0.259259,0.103448,0.149606,0.369099,0.104693
517,0.029197,0.227778,0.066667,0.037037,0.011494,0.055118,0.062589,0.007220

In [33]:
#pca로 변수 줄이기
from sklearn.decomposition import PCA

pca = PCA(n_components=4) # 주성분을 몇개로 할지 결정
printcipalComponents = pca.fit_transform(x_data)
principalDf = pd.DataFrame(data=printcipalComponents, columns = ['pc1', 'pc2','pc3','pc4'])
principalDf.head()

        pc1       pc2       pc3       pc4
0  0.088897 -0.103280 -0.135368 -0.021474
1 -0.011613 -0.069311  0.084246 -0.021615
2  0.162330 -0.107248  0.035053 -0.042324
3 -0.029848 -0.067329 -0.012085 -0.144353
4 -0.096605 -0.083101  0.019172 -0.034338

In [34]:
sum(pca.explained_variance_ratio_) # 약 82%설명

0.8241837629769091

In [35]:
pcaDf=pd.concat([principalDf,y_data],axis=1) 
pcaDf.to_csv('pca_result.csv', encoding='euc-kr')

In [36]:
pcaDf.head()

        pc1       pc2       pc3       pc4  cluster
0  0.088897 -0.103280 -0.135368 -0.021474        0
1 -0.011613 -0.069311  0.084246 -0.021615        0
2  0.162330 -0.107248  0.035053 -0.042324        0
3 -0.029848 -0.067329 -0.012085 -0.144353        0
4 -0.096605 -0.083101  0.019172 -0.034338        0

SVM 적용

In [39]:
from sklearn.model_selection import train_test_split

#데이터 전처리(traing, test 데이터 분할)
x_input = pcaDf.iloc[:, 1:-1]
y_input = pcaDf.iloc[:,-1]

x_train, x_test, y_train, y_test = train_test_split(x_input,y_input, test_size=0.2, random_state=0, stratify=y_input)
print(len(x_train))
print(len(y_train))
print(len(x_test))
print(len(y_test))

414
414
104
104

In [41]:
from sklearn.svm import SVC

#SVM훈련
svm_model = SVC(kernel='rbf', C=8, gamma=0.1)
svm_model.fit(x_train,y_train)

#SVM결과
print(svm_model.score(x_train, y_train))
print(svm_model.score(x_test, y_test))

0.9830917874396136
0.9807692307692307